package entities;

public enum Previous_disease {
    HISTORY_OF_MELANOMA,
    HISTORY_OF_GLAUCOMA,
    CONGESTIVE_HEART_FAILURE,
    HISTORY_OF_HEART_ATTACKS,
    HISTORY_OF_SUBSTANCE_ABUSE,
    HISTORY_PSYCHIATRIC_DISORDERS,
    HISTORY_FIBROSIS,
    PARAPLEGIA,
    DIABETES,
    HIGH_BLOOD_PRESSURE,
    PULMONARY_DISEASE

}
